services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - mongo
    env_file:
      - ./.env
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - .:/app

volumes:
  mongo-data:
